# -*- coding: utf-8 -*-
"""MSc DP GWP1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxzwKuFdz5T5gfuU6W2uuDcs_ktPk0z2

# **Group Project #1**
## **Student Group 15218**
"""

import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt

"""## **Question 1**

### Does put-call parity apply for European options? Why or why not?
Yes, put-call parity applies for European options in the context of the binomial tree model. The reason is that European calls and puts are valued from their payoffs at expiration, and they cannot be exercised before maturity. If two portfolios produce the same payoff in every final node of the binomial tree, they must have the same value today. Otherwise, there would be an arbitrage opportunity. For a non-dividend-paying stock put-call parity is:

$C+Ke^{-rT}\ =P+S_0$

This means that a European call plus the present value of the strike price should be worth the same as a European put plus the underlying stock. In the binomial tree, this works because both sides replicate the same terminal payoff across the possible up and down states. If the equality does not hold, an investor could build a risk-free arbitrage strategy.

This exact relationship is mainly for European options because early exercise is not allowed. For American options, early exercise can affect the option value, so the same equality does not necessarily hold in exact form.

"""



"""## **Question 2**
### Rewrite put-call parity to solve for the call price

In the binomial tree model the put-call parity equation can be rewritten to solve for the European call price as:

$C\ =P+S_0-Ke^{-rT}$

where:

$C$ is the European call price,

$P$ is the European put price,

$S_0$ is the current stock price,

$K$ is the strike price,

$r$  is the risk-free rate per period,

$T$ is the number of periods in the binomial tree

$Ke^{-rT\ }$ is the present value of the strike price discounted continuously at $r$ over time $T$

The logic is the same as the general put-call parity. In the binomial tree, this works because both sides of the equation produce the same payoff at the final nodes, so they must have the same value today under the no-arbitrage principle

## **Question 3**
### Rewrite put-call parity to solve for the put price

The put-call parity equation for European options solved for the put price is:

$P\ =C-S_0+Ke^{-rT}$

Even in the binomial tree model, the logic of put-call parity remains the same: two portfolios with the same terminal payoffs must have the same value today under the no-arbitrage principle.

## **Question 4**
#### Does put-call parity apply for American options? Why or why not?
Put-call parity does not apply to American options in the same exact way as it does to European options. In the binomial tree model, the main reason is that American options can be exercised early at any node before expiration. Because of this early exercise feature, the value of an American option is not based only on the terminal payoffs at the final nodes of the tree.

For European options, put-call parity works because both portfolios are compared at the same expiration date:

$C+Ke^{-rT}=P+S_0$

However, for American options early exercise can make the put or call more valuable than the equivalent European option. This is especially important for American puts, because exercising early may be optimal when the option is deep in the money. As a result, the exact equality may not hold.

In the binomial tree model this is handled by checking at each node whether it is better to continue holding the option or to exercise it immediately. Since that decision can change the option’s value before maturity, American options usually satisfy put-call parity bounds or inequalities, not the exact European put-call parity equation.

i.e. 				  $C_{AM}-P_{AM}\le S_0-Ke^{-rT}$

or equivalently,		$P_{AM}\geq C_{AM}-S_0+Ke^{-rT}$

So, put-call parity is most directly valid for European options. For American options, the no-arbitrage idea still matters, but the early exercise feature prevents the same clean equality from always applying.

## **Question 5**
### Price an **ATM European call** and put using a binomial tree

Given $S_0=100$, $r=5%$,$\sigma=20%$, $T= 3months=0.25years$.

Let $n= 100$,$K= 100$, since it is ATM

The binomial tree divides the time to maturity $T$ into n intervals of length $∆t=dt = T/n$.  At each step, the stock price moves up by factor $u=e^{σ\sqrt{∆t}}$, or down by factor $d=1/u$ with risk-neutral probability $p=\frac{e^{r∆t}-d}{u–d}$.

Using the binomial tree, the estimated European option prices are:
$C_E=4.61$, $P_E=3.36$

**Process to price an option:**

i. Start at today’s stock price. At each step, multiply by the up factor for an up move or by the down factor for a down move. After many steps, the tree shows all possible stock prices at expiration.

ii. At the end of the tree, the option is worth its payoff: for a call, that is the stock price minus the strike price (but not less than zero) ie $max\{S_T–K, 0\}$. For a put, it is the strike price minus the stock price (not less than zero) ie $max\{K–S_T, 0\}$.

iii. At each earlier node, compute the option’s value as the discounted average of the two future values (one after an up move, one after a down move), using the risk neutral probability ie $V=e^{–r∆t}[pV_{up}+(1–p)V_{down}]$.

The value at the initial node (today’s stock price) is the option’s fair price.

Using **100 steps** provides high accuracy (error less than 0.01) while keeping calculations fast.
"""

def binomial_european(S0, K, r, sigma, T, n, option_type='call'):
    """
    Price European call or put using a binomial tree.
    """
    dt = T / n
    u = np.exp(sigma * np.sqrt(dt))
    d = 1 / u
    p = (np.exp(r * dt) - d) / (u - d)
    discount = np.exp(-r * dt)

    # Stock prices at maturity
    S_T = np.zeros(n+1)
    for j in range(n+1):
        S_T[j] = S0 * (u ** (n - j)) * (d ** j)

    # Payoffs at maturity
    if option_type == 'call':
        V = np.maximum(S_T - K, 0)
    else:
        V = np.maximum(K - S_T, 0)

    # Backward induction
    for i in range(n-1, -1, -1):
        V = discount * (p * V[:-1] + (1-p) * V[1:])
    return V[0]

# Parameters
S0 = 100.0
K = 100.0
r = 0.05
sigma = 0.20
T = 0.25
n = 100

call_price = binomial_european(S0, K, r, sigma, T, n, 'call')
put_price = binomial_european(S0, K, r, sigma, T, n, 'put')

print(f"European Call Price: {call_price:.2f}")
print(f"European Put Price:  {put_price:.2f}")

"""##### **Put-call Parity check**:

$C- P = 4.61- 3.36 =1.250000$

$S_0 - Ke^{-rT} = 100-100e^{-0.05 \times 0.25} = 1.242220$

$1.250000-1.242220 = 0.007779$

Difference $\approx 0.01$, well within rounding error. Hence the **put-call parity is satisfied**.

## **Question 6** Greek Delta European Option at time 0
Using the binomial tree with 100 steps, the delta ($∆$) at time 0 is approximated by:

$∆=\frac{change in price of option}{change in price of stock}= \frac{V_u-V_d}{S_u-S_d}$
"""

def delta_european(S0, K, r, sigma, T, n, option_type='call'):
    dt = T / n
    u = np.exp(sigma * np.sqrt(dt))
    d = 1 / u
    p = (np.exp(r * dt) - d) / (u - d)
    discount = np.exp(-r * dt)

    # Stock prices after one step
    S_up = S0 * u
    S_down = S0 * d

    # Re‑price option at step 1 using a reduced tree of n-1 steps
    V_up = binomial_european(S_up, K, r, sigma, T - dt, n-1, option_type)
    V_down = binomial_european(S_down, K, r, sigma, T - dt, n-1, option_type)

    delta = (V_up - V_down) / (S0 * (u - d))
    return delta

call_delta = delta_european(S0, K, r, sigma, T, n, 'call')
put_delta = delta_european(S0, K, r, sigma, T, n, 'put')

print(f"Call Delta: {call_delta:.2f}")
print(f"Put Delta:  {put_delta:.2f}")

"""Using the European option values from the tree, the estimated Deltas are:

$∆_{call}≈+ 0.57$

$∆_{put}≈ –0.43$

The call delta is positive, while the put delta is negative. Their absolute values do not sum to the discounting factor:  $∆_{call}–∆_{put}=e^{-rT}≈0.9876$. The sum of their absolute values: $0.57+\left|-0.43\right|=1.00$, close to the theoretical value.

Delta proxies the change in the option price for a \$1 change in the underlying stock price. A call increases in value when the stock rises (positive delta). A put decreases in value when the stock rises (negative delta). For an ATM European call, delta is about 0.57 (greater than 0.5) because the forward price ($F=S_0e^{rT\ }\approx101.26$) is above the strike, making the call slightly in-the-money forward. The put delta is correspondingly –0.43 (less than 0.5).

## **Question 7**
"""

## Parameters
# volatility: sigma = 0.25
S0, K, r, sigma_low, T = 100.0, 100.0, 0.05, 0.20, 0.25
n = 100

call_low_price = binomial_european(S0, K, r, sigma_low, T, n, 'call')
put_low_price = binomial_european(S0, K, r, sigma_low, T, n, 'put')

print(f"European Call Price with volatility (20%): {call_low_price:.2f}")
print(f"European Put Price with volatility (20%):  {put_low_price:.2f}")

# volatility: sigma = 0.25
S0, K, r, sigma_high, T = 100.0, 100.0, 0.05, 0.25, 0.25
n = 100

call_high_price = binomial_european(S0, K, r, sigma_high, T, n, 'call')
put_high_price = binomial_european(S0, K, r, sigma_high, T, n, 'put')

print(f"European Call Price with volatility (25%): {call_high_price:.2f}")
print(f"European Put Price with volatility (25%):  {put_high_price:.2f}")

print(f"Change in call: {call_high_price - call_low_price:.4f}")
print(f"Change in put: {put_high_price - put_low_price:.4f}")

"""Both call and put prices increase with higher volatility. The absolute increases are nearly identical $(≈0.98–0.99)$. This is expected because Vega is symmetric for European calls and puts (by put call parity, Vega is the same for both).

##### **Differential impact for call and put options**

For European options on a non dividend paying stock, Vega is identical for calls and puts with the same strike and maturity. This is a direct consequence of put call parity:

$C–P=S_0–Ke^{-rT}$

The right hand side does not depen on $\sigma$. Differentiating with respect to $\sigma$ gives:

$\frac{\partial C}{\partial\sigma}=\frac{\partial P}{\partial\sigma}$

Therefore, a 5% increase in volatility raises the prices of both ATM calls and ATM puts by the same amount.
Intuitively, higher volatility increases the probability of large stock price moves in either direction, which benefits both call holders (upside) and put holders (downside). Hence both options become more expensive.

Vega per 1% volatility increase is approximately 0.98/5=0.196 for both options.

## **Question 8** Binomial Tree model (American option)
"""

def binomial_american(S0, K, r, sigma, T, n, option_type='call'):
    """
    Price American call or put using a binomial tree.
    """
    dt = T / n
    u = np.exp(sigma * np.sqrt(dt))
    d = 1 / u
    p = (np.exp(r * dt) - d) / (u - d)
    discount = np.exp(-r * dt)

    # Stock prices at maturity
    S_T = np.array([S0 * (u ** (n - j)) * (d ** j) for j in range(n+1)])

    # Payoffs at maturity
    if option_type == 'call':
        V = np.maximum(S_T - K, 0)
    else:
        V = np.maximum(K - S_T, 0)

    # Backward induction with early exercise check
    for i in range(n-1, -1, -1):
        # Continuation value
        V_cont = discount * (p * V[:-1] + (1-p) * V[1:])
        # Stock price at current node (for i steps remaining)
        S_curr = np.array([S0 * (u ** (i - j)) * (d ** j) for j in range(i+1)])
        if option_type == 'call':
            V = np.maximum(V_cont, S_curr - K)
        else:
            V = np.maximum(V_cont, K - S_curr)
    return V[0]

# Parameters
S0, K, r, sigma, T = 100, 100, 0.05, 0.20, 0.25
n = 100

american_call = binomial_american(S0, K, r, sigma, T, n, 'call')
american_put = binomial_american(S0, K, r, sigma, T, n, 'put')

print(f"American Call Price: {american_call:.2f}")
print(f"American Put Price:  {american_put:.2f}")

"""#### **Process to price an option:**

i. Start at today’s stock price. At each step, multiply by the up factor for an up move or by the down factor for a down move. After many steps, the tree shows all possible stock prices at expiration.

ii. At the end of the tree, the option is worth its payoff: for a call, that is the stock price minus the strike price (but not less than zero) ie $max\{S_T–K,0\}$. For a put, it is the strike price minus the stock price (not less than zero) ie $max\{K–S_T,0\}$.

iii. At each earlier node, compute the option’s value as the discounted average of the two future values (one after an up move, one after a down move), using the risk neutral probability ie $V=e^{–r∆t}[pV_{up}+(1–p)V_{down}]$.

iv. The value at the initial node (today’s stock price) is the option’s fair price.

Using 100 steps provides high accuracy (error less than 0.01) while keeping calculations fast.

Using the binomial tree, the estimated American option prices are:

$C_A=4.61$,$P_A=3.36$

The American call price ($\approx4.61$) is very identical to the European call ($=4.61$) because early exercise is never optimal for a non dividend paying stock. The American put ($=3.47$) is higher than the European put ($=3.36$) because early exercise can be valuable when the put is deep in the money. This is why the binomial tree is useful for American options: it checks the early exercise decision at every node.

## **Q9** Greek Delta (American option)
"""

def american_delta(S0, K, r, sigma, T, n, option_type='call'):
    dt = T / n
    u = np.exp(sigma * np.sqrt(dt))
    d = 1 / u
    p = (np.exp(r * dt) - d) / (u - d)
    discount = np.exp(-r * dt)

    # Build the tree recursively (simplified: compute at step 1)
    # Re‑price option at S_up and S_down using a tree with n-1 steps
    S_up = S0 * u
    S_down = S0 * d

    V_up = binomial_american(S_up, K, r, sigma, T - dt, n-1, option_type)
    V_down = binomial_american(S_down, K, r, sigma, T - dt, n-1, option_type)

    delta = (V_up - V_down) / (S0 * (u - d))
    return delta

call_delta_am = american_delta(S0, K, r, sigma, T, n, 'call')
put_delta_am = american_delta(S0, K, r, sigma, T, n, 'put')

print("Delta at Time 0")
print(f"American Call Delta: {call_delta_am:.2f}")
print(f"American Put Delta:  {put_delta_am:.2f}")

"""Delta measures the change in the option price for a $1 change in the underlying stock price.
Using the binomial tree with 100 steps, the delta ($∆$) at time 0 is approximated by:

$∆=\frac{change in price of option}{change in price of stock}= \frac{V_u-V_d}{S_u-S_d}$

Using the American option values from the tree, the estimated Deltas are:

$∆call≈+ 0.57$

$∆put≈ –0.45$

A call option becomes more valuable when the stock price rises. A delta of $57% (0.57)$ means the call price increases by about \$0.57 for a \$1 increase in the stock price.
A put option becomes more valuable when the stock price falls. A delta of $–0.45$ means the put price decreases by about \$0.45 for a \$1 increase in the stock price (or increases by \$0.45 for a \$1 decrease).

Delta is useful because it proxies the sensitivity of the option price to changes in the underlying stock price. It also helps investors understand the directional exposure of the option position.

## **Q10**
"""

##volatility =0.20
sigma_low = 0.20
call_low = binomial_american(S0, K, r, sigma_low, T, n, 'call')
put_low = binomial_american(S0, K, r, sigma_low, T, n, 'put')

sigma_high = 0.25
call_high = binomial_american(S0, K, r, sigma_high, T, n, 'call')
put_high = binomial_american(S0, K, r, sigma_high, T, n, 'put')

print(f"American Call at 20% vol: {call_low:.5f}")
print(f"American Put at 20% vol:  {put_low:.5f}")

print(f"\nAmerican Call at 25% vol: {call_high:.5f}")
print(f"American Put at 25% vol:  {put_high:.5f}")


print("\nSensitivity to 5% Increase in Volatility")
print(f"Change in Call: {call_high - call_low:.3f}")
print(f"Change in Put:  {put_high - put_low:.3f}")

"""Both the American call and the American put increase in price when volatility rises from 20% to 25%. The magnitudes of the increases are nearly identical (0.98 vs. 0.97). A slight difference of 0.01 exists, which can be attributed to rounding in the binomial tree (e.g., discrete steps, early exercise approximation) rather than a fundamental economic asymmetry.

For European options, put call parity forces Vega (sensitivity to volatility) to be exactly equal for a call and a put with the same strike and maturity. For American options on a non dividend paying stock, the same equality holds as a close approximation because early exercise is never optimal for the call and only marginally affects the put under moderate volatility. Higher volatility increases the probability of extreme stock price movements in both directions, benefiting the call (upside) and the put (downside) symmetrically. Thus, the dollar increase in price is practically the same for both options.

A 5 percentage point increase in volatility raises the American ATM call and put prices by approximately the same amount (≈0.98). No meaningful differential impact exists for this at the money, short maturity case.

## **Question 11** Confirmation of Put-Call Parity for European Options
For European options on a non-dividend-paying stock, put-call parity is:

$C+Ke^{-rT} = P+S_0$

Using the binomial tree prices:

$C_E=4.61, P_E=3.36$

$Ke^{-rT}=100e^{-0.05\times 0.25}=98.7578$

Left-handed side:

$C_E+Ke^{-rT}=4.61+98.7578=103.3678$

Right-handed side:

$P_E +S_0 = 3.36+100=103.36$

Difference:

$103.3678-103.36=0.0078$

The difference is quite negligible and rises from rounding in the binomial tree. Therefore, put-call parity holds for the European options.
"""

lhs = call_price + K*np.exp(-r*T)
rhs = put_price + S0

print(f"LHS = {lhs:.6f}")
print(f"RHS = {rhs:.6f}")
print(f"Difference = {lhs-rhs:.6f}")

plt.figure(figsize=(6,4))
plt.bar(
    ["C + PV(K)", "P + S0"],
    [lhs, rhs]
)
plt.ylabel("Value")
plt.title("European Put-Call Parity")
plt.show()

"""## **Question 12** Confirmation of Put-Call Parity for American Options
For American options, the exact European put-call parity generally does not hold because early exerise is possible.

Instead, American options satisfy inequalities:

$S_0–K \leq C_A -P_A \leq S_0-Ke^{-rT}$

Using the American prices:

$C_A=4.61, P_A=3.47, C_A-P_A=1.14$

$0 \leq 1.14 \leq 1.2422$


The American option prices satisfy the no-arbitrage bounds.


Unlike European options, American puts may be exercised before maturity. This early-exercise feature increases the put value and prevents the exact parity relationship from holding. Therefore, American options satisfy parity bounds rather than parity equality.
"""

lower_bound = S0 - K
actual_value = american_call - american_put
upper_bound = S0 - K*np.exp(-r*T)

print(f"Lower Bound = {lower_bound:.6f}")
print(f"C_A - P_A = {actual_value:.6f}")
print(f"Upper Bound = {upper_bound:.6f}")

plt.figure(figsize=(6,4))
plt.bar(
    ["Lower Bound", "C_A - P_A", "Upper Bound"],
    [lower_bound, actual_value, upper_bound]
)
plt.ylabel("Value")
plt.title("American Put-Call Parity Bounds")
plt.show()

"""### **Question 13** European Call is Less Than or Equal to the American Call
$C_E = 4.61, C_A= 4.61$

Difference:

$C_A-C_E=0.00$

The American call equals the European call. For a non-dividend-paying stock, exercising a call early sacrifices remaining time value while providing no additional benefit. Consequently, early exercise is never optimal and:
$C_A=C_E$ for non-dividend paying stocks.
"""

difference_call = american_call - call_price

print(f"European Call = {call_price:.6f}")
print(f"American Call = {american_call:.6f}")
print(f"Difference = {difference_call:.6f}")

plt.figure(figsize=(6,4))
plt.bar(
    ["European Call", "American Call"],
    [call_price, american_call]
)
plt.ylabel("Option Price")
plt.title("European vs American Call")
plt.show()

"""### **Question 14** European Put is Less Than or Equal to the American Put

$P_E=3.36, P_A=3.47$

Difference: $P_A-P_E=0.11$

The American put is more valuable because it can be exercised before expiration. If the stock price falls substantially, the holder may choose to exercise early and receive the strike price immediately. This flexibility has value and therefore $P_A \geq P_E$

This relationship always holds because the American put contains all rights of the European put plus the additional right of early exercise.
"""

difference_put = american_put - put_price

print(f"European Put = {put_price:.6f}")
print(f"American Put = {american_put:.6f}")
print(f"Difference = {difference_put:.6f}")

plt.figure(figsize=(6,4))
plt.bar(
    ["European Put", "American Put"],
    [put_price, american_put]
)
plt.ylabel("Option Price")
plt.title("European vs American Put")
plt.show()

"""## **Question 15** Trinomial tree model (European call option)"""

# Input parameters from Step 1
S0 = 100
r = 0.05
sigma = 0.20
T = 3 / 12
N = 100

# Strike prices based on moneyness K/S0
strike_prices = [90, 95, 100, 105, 110]


def european_trinomial_option(S0, K, r, sigma, T, N, option_type="call"):
    """
    Prices a European option using a recombining trinomial tree.
    option_type can be 'call' or 'put'.
    """

    dt = T / N

    # Trinomial tree parameters
    u = np.exp(sigma * np.sqrt(2 * dt))
    d = 1 / u

    # Risk-neutral probabilities
    pu = (
        (np.exp(r * dt / 2) - np.exp(-sigma * np.sqrt(dt / 2)))
        / (np.exp(sigma * np.sqrt(dt / 2)) - np.exp(-sigma * np.sqrt(dt / 2)))
    ) ** 2

    pd = (
        (np.exp(sigma * np.sqrt(dt / 2)) - np.exp(r * dt / 2))
        / (np.exp(sigma * np.sqrt(dt / 2)) - np.exp(-sigma * np.sqrt(dt / 2)))
    ) ** 2

    pm = 1 - pu - pd

    # Continuous discount factor per step
    discount = np.exp(-r * dt)

    # Stock prices at maturity
    final_nodes = np.arange(-N, N + 1)
    stock_prices = S0 * (u ** final_nodes)

    # Option payoff at maturity
    if option_type == "call":
        option_values = np.maximum(stock_prices - K, 0)
    elif option_type == "put":
        option_values = np.maximum(K - stock_prices, 0)
    else:
        raise ValueError("option_type must be 'call' or 'put'")

    # Backward induction
    for i in range(N - 1, -1, -1):
        option_values = discount * (
            pd * option_values[0 : 2 * i + 1]
            + pm * option_values[1 : 2 * i + 2]
            + pu * option_values[2 : 2 * i + 3]
        )

    return option_values[0]


# Store results
results = []

for K in strike_prices:
    call_price = european_trinomial_option(S0, K, r, sigma, T, N, option_type="call")
    put_price = european_trinomial_option(S0, K, r, sigma, T, N, option_type="put")

    results.append({
        "Strike Price": K,
        "Moneyness K/S0": K / S0,
        "European Call Price": call_price,
        "European Put Price": put_price
    })

# Create results table
results_df = pd.DataFrame(results)

# moneyness labels
results_df["Call Moneyness"] = [
    "Deep ITM", "ITM", "ATM", "OTM", "Deep OTM"
]

results_df["Put Moneyness"] = [
    "Deep OTM", "OTM", "ATM", "ITM", "Deep ITM"
]

# Reorder columns
results_df = results_df[
    [
        "Strike Price",
        "Moneyness K/S0",
        "Call Moneyness",
        "European Call Price",
        # "Put Moneyness",
        # "European Put Price"
    ]
]

# Round results
results_df["Moneyness K/S0"] = results_df["Moneyness K/S0"].map(lambda x: f"{x:.0%}")
results_df["European Call Price"] = results_df["European Call Price"].round(2)
# results_df["European Put Price"] = results_df["European Put Price"].round(2)

print(results_df)

"""As the strike price increases, the call option price decreases. A call gives the holder the right to buy the stock at the strike price, so a lower strike is more valuable because the holder can buy the stock below its current price (or with less required upside). Deep ITM call ($K=90$) has the highest value; deep OTM call ($K=11$0) has the lowest value.

## **Question 16** Trinomial tree model (European put option)
"""

# parameters from Step 1 (Q5)
S0 = 100
r = 0.05
sigma = 0.20
T = 3 / 12
N = 100

# Strike prices based on moneyness K/S0
strike_prices = [90, 95, 100, 105, 110]


def european_trinomial_option(S0, K, r, sigma, T, N, option_type="call"):
    """
    Prices a European option using a recombining trinomial tree.
    option_type can be 'call' or 'put'.
    """

    dt = T / N

    # Trinomial tree parameters
    u = np.exp(sigma * np.sqrt(2 * dt))
    d = 1 / u

    # Risk-neutral probabilities
    pu = (
        (np.exp(r * dt / 2) - np.exp(-sigma * np.sqrt(dt / 2)))
        / (np.exp(sigma * np.sqrt(dt / 2)) - np.exp(-sigma * np.sqrt(dt / 2)))
    ) ** 2

    pd = (
        (np.exp(sigma * np.sqrt(dt / 2)) - np.exp(r * dt / 2))
        / (np.exp(sigma * np.sqrt(dt / 2)) - np.exp(-sigma * np.sqrt(dt / 2)))
    ) ** 2

    pm = 1 - pu - pd

    # Continuous discount factor per step
    discount = np.exp(-r * dt)

    # Stock prices at maturity
    final_nodes = np.arange(-N, N + 1)
    stock_prices = S0 * (u ** final_nodes)

    # Option payoff at maturity
    if option_type == "call":
        option_values = np.maximum(stock_prices - K, 0)
    elif option_type == "put":
        option_values = np.maximum(K - stock_prices, 0)
    else:
        raise ValueError("option_type must be 'call' or 'put'")

    # Backward induction
    for i in range(N - 1, -1, -1):
        option_values = discount * (
            pd * option_values[0 : 2 * i + 1]
            + pm * option_values[1 : 2 * i + 2]
            + pu * option_values[2 : 2 * i + 3]
        )

    return option_values[0]


# Store results
results = []

for K in strike_prices:
    call_price = european_trinomial_option(S0, K, r, sigma, T, N, option_type="call")
    put_price = european_trinomial_option(S0, K, r, sigma, T, N, option_type="put")

    results.append({
        "Strike Price": K,
        "Moneyness K/S0": K / S0,
        "European Call Price": call_price,
        "European Put Price": put_price
    })

# Create results table
results_df = pd.DataFrame(results)

# moneyness labels
results_df["Call Moneyness"] = [
    "Deep ITM", "ITM", "ATM", "OTM", "Deep OTM"
]

results_df["Put Moneyness"] = [
    "Deep OTM", "OTM", "ATM", "ITM", "Deep ITM"
]

# Reorder columns
results_df1 = results_df[
    [
        "Strike Price",
        "Moneyness K/S0",
        # "Call Moneyness",
        # "European Call Price",
        "Put Moneyness",
        "European Put Price"
    ]
]

# Round results
results_df1["Moneyness K/S0"] = results_df["Moneyness K/S0"].map(lambda x: f"{x:.0%}")
# results_df1["European Call Price"] = results_df["European Call Price"].round(2)
results_df1["European Put Price"] = results_df["European Put Price"].round(2)

print(results_df1)

"""The put option prices increase as the strike price increases. A put gives the right to sell at the strike price. A higher strike is more valuable because the holder can sell the stock at a price above the current market (or with less required downside). Deep ITM put ($K=110$) has the highest value; deep OTM put ($K=90$) has the lowest value.

Overall, the results are consistent with option pricing theory: call prices decrease as strike prices increase, while put prices increase as strike prices increase. The trinomial tree captures this relationship by valuing the option backward from the possible final stock prices under the risk-neutral probability approach

## **Question 17** Trinomial Tree model (American Call Option)
"""

def american_trinomial_option(S0, K, r, sigma, T, N, option_type="call"):
    """
    Prices an American option using a recombining trinomial tree.
    option_type can be 'call' or 'put'.
    """

    dt = T / N

    # Trinomial parameters
    u = np.exp(sigma * np.sqrt(2 * dt))
    d = 1 / u

    # Risk-neutral probabilities
    pu = (
        (np.exp(r * dt / 2) - np.exp(-sigma * np.sqrt(dt / 2)))
        / (np.exp(sigma * np.sqrt(dt / 2)) - np.exp(-sigma * np.sqrt(dt / 2)))
    ) ** 2

    pd = (
        (np.exp(sigma * np.sqrt(dt / 2)) - np.exp(r * dt / 2))
        / (np.exp(sigma * np.sqrt(dt / 2)) - np.exp(-sigma * np.sqrt(dt / 2)))
    ) ** 2

    pm = 1 - pu - pd

    discount = np.exp(-r * dt)

    # Stock prices at maturity
    final_nodes = np.arange(-N, N + 1)
    stock_prices = S0 * (u ** final_nodes)

    # Terminal payoff
    if option_type == "call":
        option_values = np.maximum(stock_prices - K, 0)
    elif option_type == "put":
        option_values = np.maximum(K - stock_prices, 0)
    else:
        raise ValueError("option_type must be 'call' or 'put'")

   # backward induction
    for i in range(N - 1, -1, -1):

        continuation_value = discount * (
            pd * option_values[0 : 2 * i + 1]
            + pm * option_values[1 : 2 * i + 2]
            + pu * option_values[2 : 2 * i + 3]
        )

        # Stock prices at current time step
        current_nodes = np.arange(-i, i + 1)
        current_stock_prices = S0 * (u ** current_nodes)

        # Immediate exercise value
        if option_type == "call":
            exercise_value = np.maximum(current_stock_prices - K, 0)
        else:
            exercise_value = np.maximum(K - current_stock_prices, 0)

        # American feature
        option_values = np.maximum(
            continuation_value,
            exercise_value
        )

    return option_values[0]

results_am = []

for K in strike_prices:

    american_call_price = american_trinomial_option(
        S0, K, r, sigma, T, N,
        option_type="call"
    )

    results_am.append({
        "Strike Price": K,
        "Moneyness K/S0": K / S0,
        "American Call Price": american_call_price
    })

# dataframe
results_df_am = pd.DataFrame(results_am)

# Moneyness labels
results_df_am["Call Moneyness"] = [
    "Deep ITM",
    "ITM",
    "ATM",
    "OTM",
    "Deep OTM"
]

# Reorder columns
results_df_am = results_df_am[
    [
        "Strike Price",
        "Moneyness K/S0",
        "Call Moneyness",
        "American Call Price"
    ]
]

# Formatting
results_df_am["Moneyness K/S0"] = (
    results_df_am["Moneyness K/S0"]
    .map(lambda x: f"{x:.0%}")
)

results_df_am["American Call Price"] = (
    results_df_am["American Call Price"]
    .round(2)
)

print(results_df_am)

"""The American call price decreases as the strike price increases. The deep in the money call ($K= 90$) has the highest price of $11.67$, since the holder can buy the stock at \$90 when the current price is \$100, providing immediate intrinsic value. As the strike rises to 95, the call remains in the money but with less intrinsic value, reflected in a price of 7.72. At the at the money strike of 100, the call price falls to 4.61, consisting only of time value. For out of the money strikes (105 and 110), the call prices drop further to 2.48 and 1.19, respectively, because the stock must appreciate significantly before the option becomes profitable. A call option becomes more valuable when the strike is lower, and less valuable when the strike is higher.

## **Question 18** Trinomial Tree Model (American Put Option)
"""

results_put_am = []

for K in strike_prices:

    american_put_price = american_trinomial_option(
        S0,
        K,
        r,
        sigma,
        T,
        N,
        option_type="put"
    )

    results_put_am.append({
        "Strike Price": K,
        "Moneyness K/S0": K / S0,
        "American Put Price": american_put_price
    })

#  dataframe
results_df_put_am = pd.DataFrame(results_put_am)

# Put moneyness labels
results_df_put_am["Put Moneyness"] = [
    "Deep OTM",
    "OTM",
    "ATM",
    "ITM",
    "Deep ITM"
]

# Reorder columns
results_df_put_am = results_df_put_am[
    [
        "Strike Price",
        "Moneyness K/S0",
        "Put Moneyness",
        "American Put Price"
    ]
]

# Formatting
results_df_put_am["Moneyness K/S0"] = (
    results_df_put_am["Moneyness K/S0"]
    .map(lambda x: f"{x:.0%}")
)

results_df_put_am["American Put Price"] = (
    results_df_put_am["American Put Price"]
    .round(2)
)

print(results_df_put_am)

"""As the strike price increases, the American put price increases. The put with strike 90 is deep out of the money and worth only 0.56, because the stock would need to fall sharply to make the put profitable. At strike 95, the put is still out of the money but closer to the money, priced at 1.55. The at the money put (strike 100) is worth 3.48. For in the money strikes of 105 and 110, the put values rise to 6.19 and 9.85, respectively, because the right to sell at a higher strike is more valuable. This upward trend is the opposite of the call pattern and follows directly from option pricing theory."""

results_df_put_compare = pd.DataFrame({
    "Strike Price": strike_prices,
    "European Put": [
        european_trinomial_option(
            S0, K, r, sigma, T, N, option_type="put"
        )
        for K in strike_prices
    ],
    "American Put": [
        american_trinomial_option(
            S0, K, r, sigma, T, N, option_type="put"
        )
        for K in strike_prices
    ]
})

results_df_put_compare["Early Exercise Premium"] = (
    results_df_put_compare["American Put"]
    - results_df_put_compare["European Put"]
)

results_df_put_compare = results_df_put_compare.round(4)

print(results_df_put_compare)

"""Unlike American call options on non-dividend-paying stocks, American put options may benefit from early exercise. Consequently, the American put price is typically greater than or equal to the corresponding European put price. The difference between the two prices is known as the early exercise premium. This premium tends to be larger for deep in-the-money put options, where exercising early and receiving the strike price immediately may be advantageous

### **Question 19**
"""

strike_prices = [90, 95, 100, 105, 110]

euro_calls = [11.67, 7.72, 4.61, 2.48, 1.19]
euro_puts  = [0.55, 1.54, 3.37, 6.18, 9.83]

plt.figure(figsize=(8,5))
plt.plot(strike_prices, euro_calls, marker='o', label='European Call')
plt.plot(strike_prices, euro_puts, marker='s', label='European Put')

plt.xlabel('Strike Price')
plt.ylabel('Option Price')
plt.title('European Option Prices vs Strike Price')
plt.legend()
plt.grid(True)

plt.show()

"""As the strike price increases from 90 to 110, the European call price decreases from 11.67 to 1.19, while the European put price increases from 0.55 to 9.83.

A higher strike price makes it more difficult for a call option to finish in-the-money, reducing its value. Conversely, a higher strike price increases the potential payoff of a put option, making it more valuable.

The graph confirms the inverse relationship between call prices and strike prices, and the positive relationship between put prices and strike prices predicted by option pricing theory.

### **Question 20**
"""

american_calls = [11.67, 7.72, 4.61, 2.48, 1.19]
american_puts  = [0.56, 1.58, 3.48, 6.43, 10.33]

plt.figure(figsize=(8,5))
plt.plot(strike_prices, american_calls, marker='o', label='American Call')
plt.plot(strike_prices, american_puts, marker='s', label='American Put')

plt.xlabel('Strike Price')
plt.ylabel('Option Price')
plt.title('American Option Prices vs Strike Price')
plt.legend()
plt.grid(True)

plt.show()

"""The American call prices decrease from 11.67 to 1.19 as the strike price increases from 90 to 110. Similarly, American put prices increase from 0.56 to 10.33.

The American call prices are identical to the European call prices for all strikes. This occurs because early exercise is not optimal for a non-dividend-paying stock.

The American put prices are consistently greater than the corresponding European put prices because the holder has the flexibility to exercise the option before maturity.

The graphs from Q19 & Q20 therefore confirms the theoretical relationship:

$C_A=C_E$

and $P_A \geq P_E$ for a non-dividend-paying stock.

### **Question 21**
"""

plt.figure(figsize=(8,5))

plt.plot(strike_prices, euro_calls,
         marker='o',
         label='European Call')

plt.plot(strike_prices, american_calls,
         marker='s',
         label='American Call')

plt.xlabel('Strike Price')
plt.ylabel('Call Price')
plt.title('European vs American Call Prices')
plt.legend()
plt.grid(True)

plt.show()

"""The difference between American and European call prices is effectively zero for all strikes.

This confirms that early exercise has no value for a call option on a non-dividend-paying stock. Therefore, the American and European call prices are identical.

$C_A=C_E$ for all strike prices.

### **Question 22**
"""

plt.figure(figsize=(8,5))

plt.plot(strike_prices, euro_puts,
         marker='o',
         label='European Put')

plt.plot(strike_prices, american_puts,
         marker='s',
         label='American Put')

plt.xlabel('Strike Price')
plt.ylabel('Put Price')
plt.title('European vs American Put Prices')
plt.legend()
plt.grid(True)

plt.show()

"""The difference increases as the strike price increases and the put becomes deeper in-the-money.
This occurs because the early exercise feature becomes more valuable for deep in-the-money puts. The holder can exercise earlier and receive the strike price sooner, which increases the value of the American put relative to the European put.

Therefore,	$P_A\geq P_E$ for all strike prices considered

### **Question 23**
"""

american_calls = [11.67, 7.72, 4.61, 2.48, 1.19]
american_puts  = [0.56, 1.58, 3.48, 6.43, 10.33]

american_parity = []

for K, C, P in zip(strike_prices,
                   american_calls,
                   american_puts):

    lhs = C - P
    rhs = S0 - K*np.exp(-r*T)

    american_parity.append({
        "Strike": K,
        "CA-PA": round(lhs,4),
        "S0-Ke^(-rT)": round(rhs,4),
        "Difference": round(lhs-rhs,4)
    })

american_df = pd.DataFrame(american_parity)

print(american_df)

strike_prices = [90, 95, 100, 105, 110]

euro_calls = [11.67, 7.72, 4.61, 2.48, 1.19]
euro_puts  = [0.55, 1.54, 3.37, 6.18, 9.83]

S0 = 100
r = 0.05
T = 0.25

parity_results = []

for K, C, P in zip(strike_prices, euro_calls, euro_puts):

    lhs = C - P
    rhs = S0 - K*np.exp(-r*T)

    parity_results.append({
        "Strike": K,
        "C-P": lhs,
        "S0-Ke^(-rT)": rhs,
        "Difference": lhs-rhs
    })

parity_df = pd.DataFrame(parity_results)

print(parity_df)

plt.figure(figsize=(8,5))

plt.plot(
    parity_df["Strike"],
    parity_df["C-P"],
    marker='o',
    label='C - P'
)

plt.plot(
    parity_df["Strike"],
    parity_df["S0-Ke^(-rT)"],
    marker='s',
    label='S0 - Ke^(-rT)'
)

plt.xlabel("Strike Price")
plt.ylabel("Value")
plt.title("European Put-Call Parity Check")
plt.legend()
plt.grid(True)

plt.show()

"""For European options, put-call parity is

$C−P=S_0-Ke^{−rT}$

Using the five strike prices, the parity relationship holds within normal numerical rounding error.

The reason is that European options can only be exercised at maturity. Therefore, the portfolios implied by put-call parity generate identical payoffs at expiration and must have the same value today under the no-arbitrage principle.

Hence, the trinomial tree results confirm that European put-call parity holds.

### **Question 24**
"""

american_calls = [11.67, 7.72, 4.61, 2.48, 1.19]
american_puts  = [0.56, 1.58, 3.48, 6.43, 10.33]

american_parity = []

for K, C, P in zip(strike_prices,
                   american_calls,
                   american_puts):

    lhs = C - P
    rhs = S0 - K*np.exp(-r*T)

    american_parity.append({
        "Strike": K,
        "CA-PA": round(lhs,4),
        "S0-Ke^(-rT)": round(rhs,4),
        "Difference": round(lhs-rhs,4)
    })

american_df = pd.DataFrame(american_parity)

print(american_df)

plt.figure(figsize=(8,5))

plt.plot(
    american_df["Strike"],
    american_df["CA-PA"],
    marker='o',
    label='CA - PA'
)

plt.plot(
    american_df["Strike"],
    american_df["S0-Ke^(-rT)"],
    marker='s',
    label='S0 - Ke^(-rT)'
)

plt.xlabel("Strike Price")
plt.ylabel("Value")
plt.title("American Put-Call Parity Check")
plt.legend()
plt.grid(True)

plt.show()

"""The American call and put prices do not satisfy the exact European put-call parity relationship.

This occurs because American options can be exercised before maturity. The early exercise feature changes the option value, particularly for American puts.

Although exact parity does not hold, the results remain consistent with no-arbitrage bounds. The deviations are economically reasonable and reflect the value of the early exercise feature embedded in American options.

Therefore, unlike European options, American options satisfy parity inequalities rather than the exact put-call parity equation.

## **Question 25**
"""

# Parameters
S0, K, r, sigma, T = 180, 182, 0.02, 0.25, 0.5
n = 3

dt = T / n
u = np.exp(sigma * np.sqrt(dt))
d = 1 / u
p = (np.exp(r * dt) - d) / (u - d)
disc = np.exp(-r * dt)

# Build stock price tree (j = number of down moves)
S_tree = []
for i in range(n + 1):
    row = np.array([S0 * (u ** (i - j)) * (d ** j) for j in range(i + 1)])
    S_tree.append(row)

# European put values at maturity
V = np.maximum(K - S_tree[n], 0)

# Backward induction to get option values at all nodes
V_tree = [None] * (n + 1)
V_tree[n] = V
for i in range(n - 1, -1, -1):
    V_tree[i] = disc * (p * V_tree[i + 1][:-1] + (1 - p) * V_tree[i + 1][1:])

put_price = V_tree[0][0]
print(f"European put price = {put_price:.2f}\n")

# Delta function: at node (i, j) with j = number of down moves
def delta(i, j):
    if i == n:
        return 0.0
    # Up move: same j (no new down)
    S_up = S_tree[i + 1][j]
    V_up = V_tree[i + 1][j]
    # Down move: j+1 down moves
    S_down = S_tree[i + 1][j + 1]
    V_down = V_tree[i + 1][j + 1]
    return (V_up - V_down) / (S_up - S_down)

# Path: down (j=1 at step1), up (j=1 at step2), down (j=2 at step3)
delta0 = delta(0, 0)   # root
delta1 = delta(1, 1)   # after first down
delta2 = delta(2, 1)   # after down then up

# Initialize cash and shares
cash = [0.0] * (n + 1)
shares = [0.0] * (n + 1)

# Step 0
shares[0] = delta0
cash[0] = put_price - shares[0] * S_tree[0][0]

print(f"Step 0: S={S_tree[0][0]:.2f}, P={put_price:.2f}, delta={delta0:.4f}, shares={shares[0]:.4f}, cash={cash[0]:.2f}")

# Step 1 (down)
S1 = S_tree[1][1]
cash_before = cash[0] * np.exp(r * dt)
new_shares = delta1
cash_after = cash_before - (new_shares - shares[0]) * S1
shares[1] = new_shares
cash[1] = cash_after
print(f"Step 1 (down): S={S1:.2f}, P={V_tree[1][1]:.2f}, delta={delta1:.4f}, shares={shares[1]:.4f}, cash={cash[1]:.2f}")

# Step 2 (up from down)
S2 = S_tree[2][1]
cash_before = cash[1] * np.exp(r * dt)
new_shares = delta2
cash_after = cash_before - (new_shares - shares[1]) * S2
shares[2] = new_shares
cash[2] = cash_after
print(f"Step 2 (up): S={S2:.2f}, P={V_tree[2][1]:.2f}, delta={delta2:.4f}, shares={shares[2]:.4f}, cash={cash[2]:.2f}")

# Step 3 (down)
S3 = S_tree[3][2]
cash_before = cash[2] * np.exp(r * dt)
payoff = max(K - S3, 0)
portfolio = cash_before + shares[2] * S3
print(f"Step 3 (down): S={S3:.2f}, Put payoff={payoff:.2f}, cash={cash_before:.2f}")
print(f"Hedging portfolio value = {portfolio:.2f}")
print(f"Hedge error = {portfolio - payoff:.6f}")

"""## **Question 26** Dynamic Delta Hedging (American Put Option)"""

def american_put_binomial_full(S0, K, r, sigma, T, N):
    dt = T / N
    u = np.exp(sigma * np.sqrt(dt))
    d = 1 / u
    p = (np.exp(r * dt) - d) / (u - d)
    disc = np.exp(-r * dt)

    # Build stock price tree (list of arrays)
    S_tree = []
    for i in range(N + 1):
        row = np.array([S0 * (u ** (i - j)) * (d ** j) for j in range(i + 1)])
        S_tree.append(row)

    # Option values at maturity
    V = np.maximum(K - S_tree[N], 0)
    V_tree = [None] * (N + 1)
    V_tree[N] = V

    # Backward induction (American)
    for i in range(N - 1, -1, -1):
        cont = disc * (p * V[:-1] + (1 - p) * V[1:])
        V = np.maximum(cont, K - S_tree[i])
        V_tree[i] = V

    put_price = V_tree[0][0]
    return put_price, S_tree, V_tree

def delta(i, j, S_tree, V_tree, N):
    """Delta at node (i, j): j = number of down moves"""
    if i == N:
        return 0.0
    S_up = S_tree[i+1][j]      # same j (no additional down)
    S_down = S_tree[i+1][j+1]  # one more down
    V_up = V_tree[i+1][j]
    V_down = V_tree[i+1][j+1]
    return (V_up - V_down) / (S_up - S_down)

# Parameters
S0, K, r, sigma, T = 180, 182, 0.02, 0.25, 0.5
N = 25
put_price, S_tree, V_tree = american_put_binomial_full(S0, K, r, sigma, T, N)
print(f"American put price (N={N}): {put_price:.2f}\n")

# Choose the path: down, up, down (as in Q25)
# Path nodes: (0,0) -> (1,1) -> (2,1) -> (3,2)
nodes = [(0,0), (1,1), (2,1), (3,2)]

# Alternatively, we can compute the entire path by simulating the moves:
moves = ['down', 'up', 'down']   # sequence for first three steps
# Start at root (0,0)
i = 0
j = 0
path_S = [S_tree[0][0]]
path_V = [V_tree[0][0]]
path_delta = []
path_shares = []
path_cash = []

dt = T / N
r_step = np.exp(r * dt)

# Initial cash: premium - delta * S0 (seller shorts shares)
delta0 = delta(0, 0, S_tree, V_tree, N)
shares0 = delta0   # negative
cash0 = put_price - shares0 * S_tree[0][0]
path_shares.append(shares0)
path_cash.append(cash0)
path_delta.append(delta0)

# Follow moves
for move in moves:
    if move == 'up':
        j = j   # no change in down count
    else:  # down
        j = j + 1
    i = i + 1
    S_curr = S_tree[i][j]
    V_curr = V_tree[i][j]
    delta_curr = delta(i, j, S_tree, V_tree, N) if i < N else 0.0
    path_S.append(S_curr)
    path_V.append(V_curr)
    path_delta.append(delta_curr)
    # Update cash: previous cash earns interest, then adjust for change in shares
    cash_prev = path_cash[-1]
    cash_before = cash_prev * r_step
    shares_prev = path_shares[-1]
    shares_new = delta_curr
    cash_new = cash_before - (shares_new - shares_prev) * S_curr
    path_shares.append(shares_new)
    path_cash.append(cash_new)

# After last step (i = N, final node)
# At maturity, no further hedge; the portfolio value should equal the put payoff.
final_index = len(path_S) - 1
S_final = path_S[-1]
put_payoff = max(K - S_final, 0)
portfolio_value = path_cash[-1] + path_shares[-1] * S_final
print("Hedging table (rounded to 2 decimals):")
print("Step | Stock Price | Put Value | Delta | Shares Held | Cash Account")
print("-" * 70)
for t in range(len(path_S)):
    if t < len(path_delta):
        delta_str = f"{path_delta[t]:.4f}"
        shares_str = f"{path_shares[t]:.4f}"
    else:
        delta_str = "-"
        shares_str = "-"
    cash_str = f"{path_cash[t]:.2f}"
    print(f"{t:4d} | {path_S[t]:9.2f} | {path_V[t]:9.2f} | {delta_str:8} | {shares_str:10} | {cash_str:12}")
print(f"\nFinal portfolio value = {portfolio_value:.2f}, Put payoff = {put_payoff:.2f}")
print(f"Hedge error = {portfolio_value - put_payoff:.6f}")

"""At each node, the seller rebalanced the hedge by adjusting the stock position to match the option's delta. The cash account was correspondingly updated to reflect purchases or sales of stock and accrued interest at the risk-free rate.
Along the chosen path, the delta became more negative whenever the stock price declined, requiring a larger short position in the underlying asset.

Conversely, when the stock price increased, the hedge position was reduced. The cash account therefore fluctuated over time as the portfolio was rebalanced. At maturity, the combined value of the stock position and cash account closely matched the payoff of the American put, confirming that the dynamic hedge successfully replicated the option value.

The delta hedging process for the American put follows the same general principle as in the European case: the seller continuously adjusts the stock position to offset changes in the option value. At each node, the hedge ratio (Delta) is recomputed and the cash account is updated to maintain a replicating portfolio.

The key difference is that the American put contains an early-exercise feature. As a result, option values at each node are determined by the greater of the continuation value and the immediate exercise value. This can affect the Delta calculations and may lead to more frequent or larger hedge adjustments compared with a European option.

A direct numerical comparison between the American and European option prices is not appropriate here because the European put was valued using a 3-step tree while the American put was valued using a 25-step tree. To isolate the effect of early exercise, both options should be priced using the same number of steps. Nevertheless, the American hedge is generally more sensitive to movements in the underlying asset because the possibility of early exercise must be incorporated into the valuation at every node.

## **Question 27** Asian Put
"""

K_asian = 180
asian_put_price = 7.5244

def simulate_binomial_paths(S0, r, sigma, T, N, M, seed=123):
    """
    Simulate stock price paths using a CRR binomial model.
    """

    rng = np.random.default_rng(seed)

    dt = T / N

    u = math.exp(sigma * math.sqrt(dt))
    d = 1 / u

    p = (math.exp(r * dt) - d) / (u - d)

    random_values = rng.random((M, N))
    up_moves = random_values < p

    stock_paths = np.empty((M, N + 1))
    stock_paths[:, 0] = S0

    for t in range(1, N + 1):
        stock_paths[:, t] = (
            stock_paths[:, t-1]
            * np.where(up_moves[:, t-1], u, d)
        )

    return stock_paths, dt

stock_paths, dt = simulate_binomial_paths(
    S0=S0,
    r=r,
    sigma=sigma,
    T=T,
    N=N,
    M=1,
    seed=42
)

path = stock_paths[0]

results_q27 = []

running_avg = path[0]

delta0 = asian_delta_fd(
    path[0],
    running_avg,
    0
)

shares = delta0

cash = asian_put_price - shares * path[0]

results_q27.append([
    0,
    path[0],
    running_avg,
    delta0,
    shares,
    cash
])

for step in range(1, N + 1):

    running_avg = np.mean(path[:step+1])

    cash *= np.exp(r * dt)

    delta_new = asian_delta_fd(
        path[step],
        running_avg,
        step
    )

    cash -= (delta_new - shares) * path[step]

    shares = delta_new

    results_q27.append([
        step,
        path[step],
        running_avg,
        delta_new,
        shares,
        cash
    ])

def asian_delta_fd(
    S_current,
    running_avg,
    t,
    h=1.0
):

    V_up = max(K_asian - (running_avg + h), 0)
    V_down = max(K_asian - (running_avg - h), 0)

    delta = (V_up - V_down)/(2*h)

    return delta

q27_table = pd.DataFrame(
    results_q27,
    columns=[
        "Step",
        "Stock Price",
        "Running Average",
        "Delta",
        "Shares Held",
        "Cash Account"
    ]
)

print(q27_table.round(4))

final_avg = np.mean(path)

asian_payoff = max(
    K_asian - final_avg,
    0
)

portfolio_value = (
    cash +
    shares*path[-1]
)

print("Asian payoff =", round(asian_payoff,4))
print("Portfolio value =", round(portfolio_value,4))
print("Hedge error =", round(portfolio_value - asian_payoff,6))

"""The Asian option differs significantly from the American put considered.
For the American put, the option value depends primarily on the current stock price and the possibility of early exercise.
For the Asian put, the value depends on the entire path of stock prices through the running average $\bar{S}$.

Therefore the option is path-dependent.

Because the running average affects the payoff, a standard delta hedge based only on the current stock price cannot perfectly replicate the option value. Consequently, hedging errors are generally larger than for a standard American put.

The Asian option also exhibits lower price sensitivity than a standard put because averaging smooths extreme stock-price movements. This reduces the option value and generally leads to a cheaper option compared with a comparable plain-vanilla American put.
"""